### ISSUE TITLE
[REQ] Derive Server Profile from Template

### ISSUE THREAD

**Issue by dsoper2** [CiscoDevNet/terraform-provider-intersight#151]
Customer request to derive Server Profiles from Templates.  The UI does this with the MoCloners resource, but I don't see that resource available from the provider:

Request URL: https://intersight.com/api/v1/bulk/MoCloners
Request Method: POST
Sources: [{Moid: "...", ObjectType: "server.ProfileTemplate"}]
Targets: [{Name: "SP-Template_DERIVED-1", ObjectType: "server.Profile",…}]

**Comment by meghana-rajashekar** [comment]
### Resource available in latest version 1.0.22
The latest version now supports the MoCloner resource which can be used to clone server profile from a template.
Here's an example config:

``` hcl
resource "intersight_bulk_mo_cloner" "clone_server1"{
       sources {
               class_id = "server.ProfileTemplate"
               object_type = "server.ProfileTemplate"
               moid = intersight_server_profile_template.template1.moid
       }
       targets {
               class_id = "server.Profile"
               object_type = "server.Profile"
               additional_properties = jsonencode({
            Name = "demotest3_DERIVED-1"
            Description = "Sample description"
        })
       }
}
```
#### Note
Here, the properties of server.Profile, i.e., the "Name" and "Description" are being passed as additional_properties in json format. This is because the "targets" property can be any resource that terraform supports, so validation of fields against any single resource is not possible. However when it's passed as additonal_properties, it gets added to the payload as it happens otherwise.

#### Payload generated for the above config:
``` bash
{"ClassId":"bulk.MoCloner","ObjectType":"bulk.MoCloner","Sources":[{"ClassId":"","Moid":"61fbac9477696e2d31194a51","ObjectType":"server.ProfileTemplate"}],"Targets":[{"ClassId":"","Description":"Sample description","Moid":"","Name":"demotesting_DERIVED-4","ObjectType":"server.Profile"}]}
```

**Comment by jerewill-cisco** [comment]
Just to clarify the example above, this resource requires a lifecycle block to ignore change... otherwise Terraform will plan endless failed operations.  Each attempt to delete the created resource will fail because the delete operation is not supported by the provider.  The subsequent operations to create the resources will fail because the object already exists and would conflict.

```
resource "intersight_bulk_mo_cloner" "example" {
  # this will create three profiles due to the way the range function works...  1, 2, and 3
  for_each = toset(formatlist("%s", range(1, 4)))

  sources {
    object_type = intersight_server_profile_template.example-fi-attached.object_type
    moid        = intersight_server_profile_template.example-fi-attached.moid
  }

  targets {
    object_type = "server.Profile"
    additional_properties = jsonencode({
      Name = format("example-%s", each.key)
    })
  }

  lifecycle {
    ignore_changes = all
  }

}
```

**Comment by Philbow** [comment]
Question:
* I used intersight_bulk_mo_cloner as suggested to derive my profile from a template.
* Once I update the template (e.g add a policy to the template), the change does not get propagated to the profile
* Any idea on how to solve this?

**Comment by Philbow** [comment]
> Question:
> 
> * I used intersight_bulk_mo_cloner as suggested to derive my profile from a template.
> * Once I update the template (e.g add a policy to the template), the change does not get propagated to the profile
> * Any idea on how to solve this?

In case someone is searching for the solution. I did a bit of reverse engineering and Intersight UI seems to use api/v1/bulk/MoMergers when navigation through the template to update the profile. There is an equivalent reource called intersight_bulk_mo_merger which then updates the policies in the profile.
