### ISSUE TITLE
[BUG] Policies attached both 'to' and 'from' profiles can fail to fetch data during Plan operations causing improper drift detection [Backend: INTERSIGHT-9800]

### ISSUE THREAD

**Issue by jerewill-cisco** [CiscoDevNet/terraform-provider-intersight#170]
**Description**
Policy resources can fail to fetch data from Intersight with the following error...

> Error fetching plan data
>undefined is not an object (evaluating 'm[b].isObjectType')

Due to this failure, the resource appears to have drifted and is updated during the next apply after the situation below is created and every subsequent apply.

The problem appears to occur only when a policy is both attached "to" a profile as well as being attached "from" another profile.  For example, due to [issue 166](https://github.com/CiscoDevNet/terraform-provider-intersight/issues/166), when an `intersight_snmp_policy` is attached to a `intersight_fabric_switch_profile` using a profiles block in the policy while that same policy is attached to an `intersight_server_profile` using a policy_bucket block in the profile.

This issue does not appear to occur if a given policy is ONLY attached in one way or the other.

**To Reproduce**
```
resource "intersight_fabric_switch_cluster_profile" "example" {
  name = "example"
  type = "instance"
}

resource "intersight_fabric_switch_profile" "example" {
  for_each = toset(["A", "B"])

  name = "example-${each.key}"
  type = "instance"

  switch_cluster_profile {
    moid = intersight_fabric_switch_cluster_profile.example.moid
  }
}


resource "intersight_snmp_policy" "disabled" {
  name = "disabled"
  enabled    = false
  v2_enabled = false
  v3_enabled = false

  dynamic "profiles" {
    for_each = intersight_fabric_switch_profile.example
    content {
      moid        = profiles.value.moid
      object_type = profiles.value.object_type
    }
  }

}

resource "intersight_server_profile" "example" {
  name = "example"

  target_platform = "FIAttached"

  policy_bucket {
    moid        = intersight_snmp_policy.disabled.moid
    object_type = intersight_snmp_policy.disabled.object_type
  }
}
```
**Expected behavior**
The policy resource should be able to be refreshed during the plan operation and drift should be correctly detected.

**Provider Version :** v1.0.22

**Comment by jerewill-cisco** [comment]
To clarify further behavior, after the fail-to-plan occurs the subsequent apply operation of the policy resource removes the policy attachments made from the profile/template resource using the policy_bucket syntax leaving only the policy attachments made from the policy resource using the profiles syntax.

**Comment by meghana-rajashekar** [comment]
This issue is due to the following reason:
#### When a policy is attached using policy bucket, the policy's profiles property is updated as well.
As a result, **server.Profile** is added to the **snmp policy** profiles in the background in this scenario. However, on the next apply, TF notices a change in the **snmp policy** profiles property and sees a new profile added to it. This is in disagreement with the config you've provided.
This results in the server.Profile being removed from policy's profile.

As a solution, I recommend using **policy bucket** for both profiles or attaching both **profiles** to the policy. However, policy bucket is not currently supported by fabric.SwitchProfile in this instance. I recommend that you attach both profiles to the policy.

#### The below config works as expected and detects no drift on subsequent applies without change:
``` hcl
resource "intersight_fabric_switch_cluster_profile" "example" {
  name = "example"
  type = "instance"
}

resource "intersight_fabric_switch_profile" "example" {
  for_each = toset(["A", "B"])

  name = "example-${each.key}"
  type = "instance"

  switch_cluster_profile {
    moid = intersight_fabric_switch_cluster_profile.example.moid
  }
}


resource "intersight_snmp_policy" "disabled" {
  name       = "test-snmp"
  enabled    = false
  v2_enabled = false
  v3_enabled = false

  dynamic "profiles" {
    for_each = intersight_fabric_switch_profile.example
    content {
      moid        = profiles.value.moid
      object_type = profiles.value.object_type
    }
  }
  profiles {
	moid = intersight_server_profile.example.moid
	object_type = intersight_server_profile.example.object_type
  }

}

resource "intersight_server_profile" "example" {
  name = "example"
  target_platform = "FIAttached"
}
```

**Comment by jerewill-cisco** [comment]
Just to clarify... this issue has not been resolved.  The approach from @meghana-rajashekar is a workaround.

**Comment by meghana-rajashekar** [comment]
> Just to clarify... this issue has not been resolved. The approach from @meghana-rajashekar is a workaround.

#### @jerewill-cisco Your config is clearly asking the TF to have the profiles property of the policy to only contain the switch_profile(attachment through profiles).
However this raises a conflict as attachment through policy_bucket also adds the server.Profile to policy's **profiles** field but now since your config states it should only have switch profile, it tends to remove the server.Profile from **profiles** of the policy.

And this is how is Terraform is intended to work as it doesn't know the behaviour of policy_bucket which happens in the background. It tries to make changes to reflect your config file.
Also, unless switch_profile supports the policy_bucket, I'm afraid this could be the recommended way to achieve policy attachment on both profiles.

**Comment by mohamuni** [comment]
Hi @jerewill-cisco ,

When snmp policy is added to server profile's policy bucket, in background server.Profile is added to the snmp policy profiles. On subsequent apply terraform notices that new profile(i.e server profile) is being added snmp policy profiles which contradicts with terraform configuration provided which expects only switch profile which causes drift. 

The above mentioned operations can be achieved without observing drifts by using policy buckets in switch profile. Below mentioned example demonstrates usage of policy buckets with switch profile to achieve required operations without any drifts.

```

resource "intersight_fabric_switch_cluster_profile" "example" {
  name = "example"
  type = "instance"
  organization {
        object_type = "organization.Organization"
        moid = data.intersight_organization_organization.organization.id
    }
}

resource "intersight_fabric_switch_profile" "example" {
  for_each = toset(["A", "B"])

  name = "example-${each.key}"
  type = "instance"

  switch_cluster_profile {
    moid = intersight_fabric_switch_cluster_profile.example.moid
  }
  policy_bucket {
    moid        = intersight_snmp_policy.disabled.moid
    object_type = intersight_snmp_policy.disabled.object_type
  }
}


resource "intersight_snmp_policy" "disabled" {
  name = "disabled"
  enabled    = false
  v2_enabled = false
  v3_enabled = false
  organization  {
        object_type = "organization.Organization"
        moid = data.intersight_organization_organization.organization.id
    }
}

resource "intersight_server_profile" "example" {
  name = "example"

  target_platform = "FIAttached"
  organization  {
        object_type = "organization.Organization"
        moid = data.intersight_organization_organization.organization.id
    }

  policy_bucket {
    moid        = intersight_snmp_policy.disabled.moid
    object_type = intersight_snmp_policy.disabled.object_type
  }
}

data "intersight_organization_organization" "organization" {
  name = "default"
}
```

Please let us know in case of any concerns.

**Comment by the-akhil-nair** [comment]
Closing the issue as it is working as expected. If you face any issue please re-open the issue.
