### ISSUE TITLE
[BUG] ssh_user on intesight_kubernetes_cluster_profile doesn't get applied

### ISSUE THREAD

**Issue by cgascoig** [CiscoDevNet/terraform-provider-intersight#172]
**Describe the bug**
When setting management_config.ssh_user on intersight_kuberentes_cluster_profile it doesn't get included in the API request to intersight and the API default "iksadmin" is always populated. This results in updates on every apply that have no effect

**To Reproduce**

```
resource "intersight_kubernetes_cluster_profile" "this" {
...
  management_config {
  ...
    ssh_user = "testiksadmin"
  }
}
```

Run `terraform apply`

```
  # module.cg-tf-mod-test-deleteme.module.cluster_profile.intersight_kubernetes_cluster_profile.this will be updated in-place
  ~ resource "intersight_kubernetes_cluster_profile" "this" {
...
      ~ management_config            = [
          ~ {
              ~ ssh_user              = "iksadmin" -> "testiksadmin"
                # (9 unchanged elements hidden)
```

**Expected behavior**
The ssh_user attribute should be set in Intersight. 

**Provider Version :** v1.0.22

**Comment by meghana-rajashekar** [comment]
@cgascoig ssh_user in the management_config is a readOnly property which can't be set by terraform. However because it was a nested field, it was being shown as a diff.
#### The latest provider release(1.0.23) has been updated to throw a warning if the user tries to set any readOnly properties. In this case, there would not be any confusions as to why the values aren't been reflected after a successful apply.
