### ISSUE TITLE
[BUG] intersight_vnic_eth_adapter_policy and intersight_vnic_fc_adapter_policy inproperly warning read only attributes [Backend: INTERSIGHT-9035]

### ISSUE THREAD

**Issue by scotttyso** [CiscoDevNet/terraform-provider-intersight#177]
**Describe the bug**

intersight_vnic_eth_adapter_policy inproperly warning that completion_queue_settings.ring_size is a read only attribute

intersight_vnic_fc_adapter_policy warning that rx_queue_settings.0.nr_count and tx_queue_settings.0.nr_count are read only attributes

```hcl
│ Warning: Cannot set read-only property: [completion_queue_settings.0.ring_size]
│ 
│   with intersight_vnic_eth_adapter_policy.ethernet_adapter_policies["default"],
│   on ethernet_adapter_policies.tf line 192, in resource "intersight_vnic_eth_adapter_policy" "ethernet_adapter_policies":
│  192:     ring_size = each.value.completion_ring_size
│ 
│ (and 9 more similar warnings elsewhere)
╵
╷
│ Warning: Cannot set read-only property: [rx_queue_settings.0.nr_count]
│ 
│   with intersight_vnic_fc_adapter_policy.fibre_channel_adapter_policies["Windows"],
│   on fibre_channel_adapter_policies.tf line 144, in resource "intersight_vnic_fc_adapter_policy" "fibre_channel_adapter_policies":
│  144:     nr_count  = 1
│ 
│ (and 10 more similar warnings elsewhere)
╵
╷
│ Warning: Cannot set read-only property: [tx_queue_settings.0.nr_count]
│ 
│   with intersight_vnic_fc_adapter_policy.fibre_channel_adapter_policies["Windows"],
│   on fibre_channel_adapter_policies.tf line 152, in resource "intersight_vnic_fc_adapter_policy" "fibre_channel_adapter_policies":
│  152:     nr_count  = 1
│ 
│ (and 10 more similar warnings elsewhere)
```

But you can see that the intersight_vnic_eth_adapter_policy inproperly  completion_queue_settings.ring_size is modified when a plan is run

```hcl
  # intersight_vnic_fc_adapter_policy.fibre_channel_adapter_policies["Target"] will be updated in-place
  ~ resource "intersight_vnic_fc_adapter_policy" "fibre_channel_adapter_policies" {
        id                          = "621662c1edac77124df7fbb3"
        name                        = "Target"
      ~ rx_queue_settings           = [
          ~ {
              ~ ring_size             = 2048 -> 64
                # (4 unchanged elements hidden)
            },
        ]
```

**To Reproduce**
1. Resource for '...'
2. Run `terraform apply` '....'
3. Update resource '....'

**Expected behavior**

**Screenshots and Terraform configurations**

**Provider Version :** v1.0.23
I have not seen this issue before v1.0.23

**Additional context**

**Comment by meghana-rajashekar** [comment]
#### @scotttyso The latest provider version v1.0.23 was updated to throw a warning when user tries to set value for any readOnly property. The provider doesn't set the readOnly properties if passed in config. This was added in order to avoid any confusions.

You can check the Apidocs if the warnings thrown are for readOnly attributes only here:
#### intersight_vnic_eth_adapter_policy: https://intersight.com/apidocs/apirefs/vnic/EthAdapterPolicies/model/
#### intersight_vnic_fc_adapter_policy: https://intersight.com/apidocs/apirefs/vnic/FcAdapterPolicies/model/
The properties mentioned in this case are readOnly properties with default values set by backend.
For eg: **completion_queue_settings.0.ring_size** is set **1** by backend. If it has been updated to 1 after apply, it should be because of the backend setting to 1 and not the value passed in the config file.

Can you please verify if the value passed for **completion_queue_settings.0.ring_size** in the config file was **1** ?
And try passing different values for this field and check if it's set.

**Comment by scotttyso** [comment]
completion_queue_settings.0.ring_size is not a read only attributes.  It does look like the nr_count (queue counts) have changed in recent updates to be read only attributes.  But I can configure ring_size both from the UI and from the API.

**Comment by scotttyso** [comment]
Issue resolved in newer providers
