### ISSUE TITLE
intersight_os_catalog datasource returns empty

### ISSUE THREAD

**Issue by techBeck03** [CiscoDevNet/terraform-provider-intersight#23]
### Problem Statement

While trying to populate an os_catalog data source, the return values are always empty

### Code snippet (with fake moid)

```hcl
data "intersight_os_catalog" "catalog" {
    moid = "867530986753098675309"
}
```

### Observed behavior

Using the Interisght API browser, i can query by moid for a given os catalog and see an expected value returned.  When i use the snippet above with the same moid the result is:

```
{
  "mode": "data",
  "type": "intersight_os_catalog",
  "name": "catalog",
  "provider": "provider[\"registry.terraform.io/ciscodevnet/intersight\"]",
  "instances": [
    {
      "schema_version": 0,
      "attributes": {
        "additional_properties": null,
        "class_id": null,
        "configuration_files": null,
        "distributions": null,
        "id": null,
        "moid": null,
        "name": null,
        "object_type": null,
        "organization": null,
        "tags": null
      },
      "sensitive_attributes": []
    }
  ]
}
```

**Comment by code-lucidal58** [comment]
What is the provider version? If not using the latest provider, please use the 0.1.3 version (latest) of the provider. Manual testing for `data.intersight_os_catalog` is working as expected. 
If you are using the latest version, please share the log of `terraform apply` after setting `export TF_LOG=debug` and replacing sensitive data.

**Comment by techBeck03** [comment]
Upgrading to `0.1.3` did allow me to search by moid and get an expected result.  As a follow up related to this topic, how would i know the `name` or `moid` of an `os_catalog` if I wanted to add an scu image (`intersight_firmware_server_configuration_utility_distributable`) to the software repository?  Would that go under the catalog named `shared`?  If not i'm lost as to how you could possibly know the `moid` without creating something in the UI and then looking at the os catalog moid.

Thanks!

**Comment by code-lucidal58** [comment]
The `catalog` parameter in `intersight_firmware_server_configuration_utility_distributable` is of type `softwarerepository.Catalog`. There is a softwareRepository Catalog for each organization in the endpoint. Hence, you have to find the catalog that is attached to your desired organization through a manual search of each result in GET softwarerepository/Catalogs. In this provider, data source filters on the basis of simple type properties only. Since, organization is a complex type property in softwarerepository.Catalog, a manual investing of the required catalog is required.

**Comment by code-lucidal58** [comment]
Closing this issue because main issue is resolved
