### ISSUE TITLE
[Question] Creating service profiles from templates

### ISSUE THREAD

**Issue by rmtilson** [CiscoDevNet/terraform-provider-intersight#260]
I know this isn't probably the correct place to ask questions. If there is a more appropriate place please let me know.

But attempting to create profiles off of templates. Thought using the intersight_server_profile resource was the correct path but that doesn't not. Just linking the template does not create a profile with the policies. Deriving a policy in the gui call the MoCloners API, which i see there is a intersight_bulk_mo_cloner resources. 

If I create using the intersight_server_profile resource provide the same policy bucket as the template while also linking to that template would that be the same as using the intersight_bulk_mo_cloner resource? I also want to assign a server which the intersight_server_profile also allows for easily.

**Comment by rmtilson** [comment]
Also worth noting that utilizing the intersight_bulk_mo_cloner, it seem this approach might limit future changes since the resource is not based off of intersight_server_profile.

**Comment by scotttyso** [comment]
@rmtilson - Please see my example here
https://github.com/terraform-cisco-modules/terraform-intersight-profiles

You can look at how I am doing Server Profiles and Templates.  I do it two different ways.  in the `templates.tf` there is an example of doing it via the bulk_mo_cloner and a bulk_mo_merge.  

There is also a small Terraform example I have here:
https://github.com/terraform-cisco-modules/easy-imm/tree/main/update_server_template

That I talk about the challenges using the rest resources above and what I use that example for.

**Comment by ropyd** [comment]
@scotttyso I noticed that you did not use 'intersight_bulk_mo_cloner' in your server-template.tf file. How exactly do you derive profiles from a template? I've tried using 'intersight_bulk_mo_cloner' but it seems like it requires something else.

**Comment by scotttyso** [comment]
@ropyd if you do this from the GUI, and open a developer tab, when you attach a template to a server profile you will notice it uses the bulk_mo_merger.  Because reservations for server profiles needs to be applied to a server profile before attaching policies, I have found that bulk_mo_merger is a better way for me to accomplish all use cases.

I have updated the code since Jan 17 and now the attach/detach works with Terraform that I couldn't get working back then, with my previous comment above.

Based on some feedback from another customer I use the ```additional_properties``` to attach and detach the templates now.  since ```src_template``` wouldn't allow using a Null value.

You can see here how I am using the ```additional_properties``` with the server profile:
https://github.com/terraform-cisco-modules/terraform-intersight-profiles/blob/main/server.tf

Note that with Terraform and how the API is built for profiles, I end up having three resources for the server profile, two for the chassis/domain profiles.  

The reason is: for reservations, if used, they need to be applied before assigning policies to the profiles, and if I use the ```intersight_bulk_mo_merger``` to a profile, I found in the past sometimes not all the policies would attach before it started the deployment.  I believe they fixed this for server profiles, but I don't know if they fixed it for chassis and domain profiles.  For now, using the additional deploy resource loop makes sure this works for me. 

For the front end of the script, See working examples here:
https://github.com/terraform-cisco-modules/easy-imm
https://github.com/terraform-cisco-modules/easy-imm/blob/main/profiles/server.ezi.yaml
https://github.com/terraform-cisco-modules/easy-imm/blob/main/templates/server.ezi.yaml

Note: If you use the modules I have created, I recommend using version 4.2.11-16711 of the modules with version 1.0.47 of the Intersight provider.  Right now, provider versions 1.0.48-1.0.50 are broken related to template merger. 

And make sure to use the YAML Schema for autocompletion and input validation.

**Comment by the-akhil-nair** [comment]
@rmtilson  I hope we answered your queries. If you have any doubts in future please create a new issue with similar tag or please feel free to re-open this issue. Closing this issue for now.
