### ISSUE TITLE
Resource intersight_adapter_config_policy has wrong type defined 

### ISSUE THREAD

**Issue by sandkum5** [CiscoDevNet/terraform-provider-intersight#43]
When I am inspecting the rest API calls in the browser, I see the "settings" and "dce_interface_settings" as array variables. 
settings [{ dce_interface_settings [{ interface_id = 0 }] }]

However, when I try to create the resource, it's accepting the values as Hashmap and not an array. 

Working Example: 
Note: Notice the settings and dce_interface_settings of type Hashmap and not an array. 

`resource "intersight_adapter_config_policy" "adapter_policy" {
  name        = "tf_adapter_policy1"             
  description = "tf_adapter_policy1_description" 
  organization {
    object_type = "organization.Organization"
  }
  settings {
    slot_id     = "MLOM" 
    object_type = "adapter.AdapterConfig"
    eth_settings {
      lldp_enabled = true
    }
    fc_settings {
      fip_enabled = true
    }
    port_channel_settings {
      enabled = true
    }

    dce_interface_settings {
      object_type  = "adapter.DceInterfaceSettings"
      fec_mode     = "cl91" 
      interface_id = 0      # 0-3 
    }
    dce_interface_settings {
      object_type  = "adapter.DceInterfaceSettings"
      fec_mode     = "cl91" 
      interface_id = 1
    }
    dce_interface_settings {
      object_type  = "adapter.DceInterfaceSettings"
      fec_mode     = "cl91" 
      interface_id = 2
    }
    dce_interface_settings {
      object_type  = "adapter.DceInterfaceSettings"
      fec_mode     = "cl91"
      interface_id = 3
    }
  }
}`

**Comment by code-lucidal58** [comment]
Terraform interprets the above configuration as 4 elements for the array `dce_interface_setting`. I understand that this is slightly confusing because the same syntax is used for Hashmap properties. But this is how terraform's HCL asks the configuration to be written. Here is an [example](https://www.terraform.io/docs/extend/schemas/schema-types.html#typeset) from terraform's documentation on how to populate elements into a property of type Set. The syntax is the same for List-type properties. Below is the image of terraform's log after running `terraform plan` on the configuration mentioned in the issue description.
<img width="784" alt="image" src="https://user-images.githubusercontent.com/16690317/108617057-3f5dc580-7439-11eb-9c60-1e7896d1b691.png">

You will notice here that the provider understands that the 4 blocks for elements on single array.

**Comment by sandkum5** [comment]
Thank you for the clarification. :)
