### ISSUE TITLE
Resource intersight_boot_precision_policy wrong property type and mismatch in property path

### ISSUE THREAD

**Issue by sandkum5** [CiscoDevNet/terraform-provider-intersight#44]
Issue-1: boot_devices property is defined as an array but it accepts the value as Hashmap. 
boot_devices {}.   should be boot_devices = [{}]

Issue-2: When inspecting the intersight api calls in the browser, I see a subtype field being sent under boot_devices. However, the terraform provider has the property defined under additional_properties. 
`
We should align the provider with the intersight api calls made using the browser to avoid confusion. 
`

`txt
Non-working: 
  boot_devices {
    name        = "testmedia"
    subtype     = "cimc-mapped-dvd"
    enabled     = true
    object_type = "boot.VirtualMedia"
  }
  
Working example: 
boot_devices {
   enabled     = true
   name        = "vmedia"
   object_type = "boot.VirtualMedia"
   additional_properties = jsonencode({
   subtype = "cimc-mapped-dvd"
   })
  }
`

**Comment by code-lucidal58** [comment]
Issue 1: Please refer #43
Issue 2: Boot Device is an array of heterogeneous elements. To maintain uniformity, the additionalProperties feature of OpenAPI Spec is used. For the provider's users, the [documentation](https://github.com/CiscoDevNet/terraform-provider-intersight/blob/master/website/docs/r/boot_precision_policy.html.markdown#allowed-types-in-additionalproperties) is updated to include details on what properties will go inside the `additional_properties` along with the syntax. You can also use this key in a scenario when (due to some unaddressed issues) the provider lags behind the production release and you want to use a property that is newly introduced, by the provider does not support that property.

**Comment by sandkum5** [comment]
Thank you for the details.
