### ISSUE TITLE
Resource intersight_server_profile missing options to link policy resources 

### ISSUE THREAD

**Issue by sandkum5** [CiscoDevNet/terraform-provider-intersight#50]
-To assign policies to server_profile, we need to use the "profiles" attribute available within policy resources. 
-In GUI, we have the option to choose policies from within the server-profile. 
-Need a similar option via terraform so we don't have to edit each policy resource tf file to link it to the server-profile. 

-------------------------------------------------------------

**Current Option:** 
resource "intersight_ntp_policy" "ntp_policy" {
  profiles {
    moid        = intersight_server_profile.server_1.id
    object_type = "server.Profile"
  }
}

-------------------------------------------------------------

**Requested Option:** 

resource "intersight_server_profile" "server_1" {
  ntp_policy {
    moid = intersight_ntp_policy.ntp_policy.id
  }
}

**Comment by code-lucidal58** [comment]
The Intersight API is designed in a way that allows attaching profiles to policies and not the reverse. Hence, the enhancements request here, will need a revamp in the API structure.  
@vvb Please correct me if I am wrong.

**Comment by sandkum5** [comment]
If we have an option to choose policies within the server-profile, I am hoping we should be able to get a similar functionality using terraform as well?

**Comment by code-lucidal58** [comment]
The feature will soon be supported in Intersight. Once it is available, the support for the same will be added to the provider

**Comment by code-lucidal58** [comment]
In the upcoming release, a profile will have a property policy_bucket. This property will be an array of references to all policies attached to the profile. Hence, it will link to policies from the profiles, contrary to link from policies to profiles in the current release through profiles property. This will help you manage profiles and policies separately.
The expected behaviour for destroying will be:
Assume a profile has 2 policies:
* Deleting the profile will not delete any policy attached to that profile
* Deleting a policy attached to a profile/profiles, will delete all the profiles, then delete the policy.

You can also join the discussion going on in #80

**Comment by code-lucidal58** [comment]
Closing this issue. Resolved with 1.0.7 release
