### ISSUE TITLE
Organization property missing from os and scu software repository 

### ISSUE THREAD

**Issue by sandkum5** [CiscoDevNet/terraform-provider-intersight#53]
Affected Resources: 
intersight_softwarerepository_operating_system_file
intersight_firmware_server_configuration_utility_distributable

In Intersight GUI, we have an option to choose Organization for the resources in question. 

However, when I try to specify an organization attribute, it fails with error: 

----------------------------------------------------------------------------------------

Error: Unsupported block type
  on create_os_repo.tf line 6, in resource "intersight_softwarerepository_operating_system_file" "esxi_custom_iso":
   6:   organization {
Blocks of type "organization" are not expected here.

Error: Unsupported block type
  on create_scu_repo.tf line 6, in resource "intersight_firmware_server_configuration_utility_distributable" "scu_ucsc":
   6:   organization {
Blocks of type "organization" are not expected here.

----------------------------------------------------------------------------------------

**Comment by code-lucidal58** [comment]
"Organization" is not a valid property for the above mentioned MOs. "Catalog" is used to identify the organization. You may refer to the apidocs or provider docs to see the allowed properties. https://www.intersight.com/apidocs/apirefs/api/v1/softwarerepository/OperatingSystemFiles/post/ 

Since no change is expected in the Intersight provider, closing this issue.
