### ISSUE TITLE
Request for organization assignment to servers

### ISSUE THREAD

**Issue by gve-vse-tim** [CiscoDevNet/terraform-provider-intersight#59]
Currently, we are able to create organizations with the provider, assign server profile related policies to that organization, but not able to place servers into that newly created organization in order to apply the server profile.

Requesting new arguments for the intersight_organization_organization resource to permit assignment of discovered servers to the organization.  An example Terraform plan would look something like this:

```
data "intersight_compute_rack_unit" "server1" {
    serial = "SERIAL_NUMBER_1"
}

data "intersight_compute_rack_unit" "server2" {
    serial = "SERIAL_NUMBER_2"
}

resource "intersight_organization_organization" "target" {
    description = "Terraform Deployed"
    name = var.target_organization

    servers = [
        data.intersight_compute_rack_unit.server1.moid,
        data.intersight_compute_rack_unit.server2.moid,
    ]
}

```

As another approach, to mimic the Intersight GUI approach - the ability to say all targets/devices/servers should be a member of this organization:

```
resource "intersight_organization_organization" "target" {
    description = "Terraform Deployed"
    name = var.target_organization

    all_devices = true
}

```

**Comment by code-lucidal58** [comment]
Terraform sits above the API layer of Intersight. Add properties that are not expected by Intersight API, but to mimic the UI would defy the essence of the provider.
To affiliate all/ some devices in the new organization, a resource group has to be created with the required level of permission or "Allow-all". This resource group is attached to the new organization.

Closing this issue because this beyond the scope of the provider.
