### ISSUE TITLE
need to decouple server profile operations from policies

### ISSUE THREAD

**Issue by dsoper2** [CiscoDevNet/terraform-provider-intersight#80]
There may be a better way to manage things (if so let me know!), but I currently have to manage server profiles along side policies that link to the profile (example module at https://github.com/terraform-cisco-modules/terraform-intersight-server-profile ).  This linkage leads to a few issues:
- complex configurations when all possible server policies are included
- problems with state if changes are made outside terraform to policies 
- difficulties with destroy.  I don't currently know of a way to destroy in a single pass, and the desired behavior would be just a profile unassign/delete without all policies being deleted as well (policies could be used by other non terraform managed profiles)

I'd like the ability to manage policies separately from profiles and just name the policies I want used by the profile (policies managed by policy specific modules and profiles managed in a module that does not modify the policies).  Ansible does this by just pulling policy names and creating links from policies where needed (or deleting them) without other modifications to the policy.

**Comment by code-lucidal58** [comment]
In the upcoming release, a profile will have a property `policy_bucket`. This property will be an array of references to all policies attached to the profile. Hence, it will link to policies from the profiles, contrary to link from policies to profiles in the current release through `profiles` property. This will help you manage profiles and policies separately.
The expected behaviour for destroying will be:
Assume a profile has 2 policies:
* Deleting the profile will not delete any policy attached to that profile
* Deleting a policy attached to a profile/profiles, will delete all the profiles, then delete the policy.

@dsoper2 will this be  the desired scenario?

**Comment by dsoper2** [comment]
That sounds good, and the destroy behavior also sounds good.  Thanks for the quick response!

**Comment by baelen-git** [comment]
Hi @code-lucidal58 

I would like to suggest a different behaviour for "Deleting a policy attached to a Profile(s)"
Instead of deleting the Profile(s) which are connected to the policy, I would prefer to return an error.
```"Policy is still attached to profile(s) "<name of the profile>". ```
 In the Intersight GUI it is also not possible to delete a Policy when it's still attached to a Profile.

Unless the profile is also in the Terraform code and is also about to be deleted, then please;
1. delete the profile 2. delete the policy

When the profile is not about to be deleted, but you only want to delete the policy, then please return the error I described above.

@dsoper2  please let me know if you would disagree

**Comment by dsoper2** [comment]
I'd agree that if a profile resource isn't defined in the config file, a destroy shouldn't delete profiles.  To hopefully clarify behavior on destroy across a few cases:
1.  Policy resource with profiles (only way I know to link policies to profiles currently).  This results in complex config files, so I'd think this doesn't see a lot of use longer term.  Destroy would delete profiles and policies (where possible).
2. Policy resource with no profiles.  This is how I'd expect policy management longer term to allow modules that cover each policy (or set of related policies).  Destroy attempts to delete the policy and errors if there are attached profiles as mentioned above.
3. Profile resource with policy_bucket.  Destroy unassigns/deletes the profile and policies are not affected.

**Comment by scotttyso** [comment]
I would be concerned about the deletion of a policy deleting all the profiles attached to it.  Honestly this would be better to block the policy deletion until it is unattached from the service profiles.  I can see that being a huge outage for customers that make a mistake.

**Comment by code-lucidal58** [comment]
@dsoper2 @scotttyso @baelen-git Apologies for the incorrect information. With the latest provider, the `destroy` behaviour is taken care of as: you can delete any policy or profile independently, irrespective of their reference to one another.
I have edited my earlier comment as well. This behaviour can be tried out in the latest provider (v1.0.7)

**Comment by scotttyso** [comment]
Thank you for clarifying.

**Comment by code-lucidal58** [comment]
Closing this issue. Resolved with 1.0.7 release
