### ISSUE TITLE
Unable to update existing resource with moid

### ISSUE THREAD

**Issue by sbraicu** [CiscoDevNet/terraform-provider-intersight#85]
Trying to update an existing resource by specifying the moid gives this error - it seems the moid is not set in the URL as requested by the API.

**terraform intersight object ID '' in the URL does not match the object ID in the request body**

how can I specify that ID - Is there any way to update an existing resource which was not created explicitly by terraform?

Use-case:
When deploying the addons at cluster deployment, the cluster profile creates automatically a cluster addon profile which needs to be updated in order to add the needed addons.
[tf_iks.txt](https://github.com/CiscoDevNet/terraform-provider-intersight/files/6400996/tf_iks.txt)

There is also an error regarding the selector field which is requested in the addon/addon_policy list inside resource_intersight_kubernetes_cluster_addon_profile.go and does not exist on intersight - commenting it in the file (lines 174-179) and recompiling the provider solved the issue.

**Comment by code-lucidal58** [comment]
Terraform allows you to import an object into its umbrella using `terraform import`. Intersight provider supports this feature. You can look into the data source documentation (https://github.com/CiscoDevNet/terraform-provider-intersight/tree/master/website/docs/d) of the respective object to review the syntax for the imports. You can refer to the following articles to understand more about the command:
* https://www.terraform.io/docs/cli/commands/import.html
* https://www.terraform.io/docs/cli/import/index.html
* https://medium.com/swlh/terraform-imports-resources-modules-for-each-and-count-bab7660c8ecd

Terraform allows you to update only those resources which exist in its statefile `terraform.tfstate`. Any other configuration is treated as a new resource.
Since, there is no fix expected for this issue, I am closing this.

**Comment by sbraicu** [comment]
Thanks. In this case it is a little bit more complex - when creating a cluster profile, the cluster profile creates a cluster addon profile by itself and that cluster addon profile is not available in the state. 
Not sure how we can import that cluster addon profile to be able to modify it as part of the same tf/process.

**Comment by code-lucidal58** [comment]
You can import the cluster addon profile into the tf, after the first `terraform apply` and do the changes.

**Comment by sbraicu** [comment]
Thanks, I know that, but it does not help on the automation. The deployment of the cluster, including addons, should happen on one terraform apply, which it seems is not possible right now using this adapter.
